### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/m2-evaluacion-intermedia-samanthacancino#1]
Really cool job @samanthacancino !!!

Here you have some tips to improve the exercise:

### JavaScript

- [x] Repeated code: `tries += 1; counterNumber.innerHTML = tries;`. Move it to the end of the function, or to an other function.
- [x] Extract the feedback painter to a function

### Advanced

- [x] Move the feedback logic to a function an execute it on each click
- [x] Move you counter logic into a function and execute it on each click
- [x] You are writing many times "trackEl.innerHTML = 'something';", what about making a function that accepts a string as param and paints it into 'trackEl'?

### HTML

- [x] Remove one H1
- [x] Add HTML elements for the game: title, label and input, button, space for feedback (`div`, `p`) and number of trials
- [x] Use a `label` to define the content of the input
- [x] Connect the label to the input using the `for` attribute of the label and the `id` of the input
- [x] Use placeholder attribute instead of value one to show a field's hint

### Steps to finish the game (for those far from the solution)

You are close to the exercise solution, but here you have a steps guide to complete it anyway ;)

1. Save a reference to DOM elements in variables
2. Generate the random number and save it to a variable
3. Init counter of trials to 0
4. Define a function that executes when the user clicks on the button, that
  - increments the counter and paints its value in the HTML
  - collect the value of the HTML input and compare it with the random number
    - if they are equal, draw a 'You Win' message
    - if it's lower, draw a 'Too short' message
    - if it's higher, draw a 'Too long' message
5. Assign a listener to the button click to execute the previous function

### Further challenges

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Make the input work when hitting enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

Let me know if you have any doubts ;)

Go for it!!

**Comment by migueldelmazo** [comment]
![](https://gph.is/1c7vGFY)

**Comment by samanthacancino** [comment]
Hello Miguel! I've fixed the issues, and added the extras. Thank you for the review!
:))

**Comment by migueldelmazo** [comment]
![](https://media.giphy.com/media/QAsBwSjx9zVKoGp9nr/giphy.gif)

**Comment by samanthacancino** [comment]
<img src="https://media.giphy.com/media/U6Fxnc2jTlBh2GKCTU/giphy.gif"/>
